ALTER TABLE orders
    ADD COLUMN payment_intent_id VARCHAR(255) DEFAULT NULL,
    ADD COLUMN payment_status ENUM('CANCELLED', 'COMPLETED', 'FAILED', 'PENDING', 'PROCESSING', 'REFUNDED') DEFAULT NULL;
